### ISSUE TITLE
Position Validation

### ISSUE THREAD

**Issue by connorprice** [RaidNode/SudokuSolver#3]
Checking if a number is valid in a certain position on the Sudoku grid.

**Comment by JoshuaMankelow** [comment]
@connorprice , There's multiple ways of doing this and I can't figure out which would be more efficient. I'm gonna push both methods into my branch in two different functions.

**Comment by JoshuaMankelow** [comment]
Wrong button

**Comment by connorprice** [comment]
I'll take a look at them now.

**Comment by connorprice** [comment]
@JoshuaMankelow I took a look at both of them and did some testing in sublime to get timings, there does not appear to be a big difference in timings so I would just go with whichever one you prefer.
